### ISSUE TITLE
הכנסת מכרז מרכזי לאתר

### ISSUE THREAD

**Issue by Shira182** [hasadna/socialpro#2]
היי, באופן נדיר, יש מכרז מרכזי שאנחנו רוצים להוסיף לאתר, בשם- מתן שירותי תפעול לגיוס והשמה של מתנדבים לשירות הלאומי במשרדי הממשלה וביחידות הסמך. מדובר במכרז שצריך להיות מקושר לשירות 'שירות לאומי אזרחי' של משרד הרווחה וגם לשירות נוסף של משרד החינוך. הוא רלוונטי גם לחינוך וגם לרווחה, שניהם מוציאים מתוקפו הזמנו עבודה. איך לדעתך נכון  להכניס אותו?

**Comment by akariv** [comment]
לאחר שיפורסם בדו״ח המכרזים של מנהל הרכש (
https://mr.gov.il/ilgstorefront/he/news/details/230920201036) המערכת שלנו
תמשוך את המידע עליו ואז יהיה אפשר לשייך אותו לשירות הרלוונטי במערכת ההזנה.

**Comment by Shira182** [comment]
מדובר במכרז מה- 3.2018, כך שהיה אמור להיות מפורסם.  יש פיתרון נקודתי שניתן לעשות במצב כזה?

**Comment by akariv** [comment]
מה מספר ההליך?

**Comment by Shira182** [comment]
[272401.pdf](https://github.com/hasadna/socialpro/files/8055412/272401.pdf)
3/2018, ההליך המלא מצורף בקובץ

**Comment by akariv** [comment]
הוספתי את האפשרות לחבר מכרזי חשב כללי דרך מערכת ההזנה.
